services:
    pdftk.managers.pdftk:
        class: SpecShaper\PdftkBundle\Managers\PdftkManager
        arguments: ["%kernel.cache_dir%", "%pdftk%"]

# example to implement in your own services.yml
#    app.manager.document:
#        class: AppBundle\Manager\DocumentManager
#        arguments:
#            - "@pdftk.managers.pdftk"
