services:
    SpecShaper\PdftkBundle\Managers\PdftkManager:
        arguments: ["%kernel.cache_dir%", "%spec_shaper_pdftk.parameters%"]

# example to implement in your own services.yml
#    app.manager.document:
#        class: AppBundle\Manager\DocumentManager
#        arguments:
#            - "@pdftk.managers.pdftk"
